// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_yaPdOtY2cCGf15Q-uzboIsY4sqR6OIE',
    appId: '1:1048561776711:web:96b57e45b9c20fee39d962',
    messagingSenderId: '1048561776711',
    projectId: 'internship-to-app',
    authDomain: 'internship-to-app.firebaseapp.com',
    storageBucket: 'internship-to-app.firebasestorage.app',
    measurementId: 'G-602VQ15ED6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQOHjTvadiA5OLve2PdHdupj4DQPGlwy0',
    appId: '1:1048561776711:ios:4a4f690e09146bf639d962',
    messagingSenderId: '1048561776711',
    projectId: 'internship-to-app',
    storageBucket: 'internship-to-app.firebasestorage.app',
    iosBundleId: 'com.example.appBottomBar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQOHjTvadiA5OLve2PdHdupj4DQPGlwy0',
    appId: '1:1048561776711:ios:4a4f690e09146bf639d962',
    messagingSenderId: '1048561776711',
    projectId: 'internship-to-app',
    storageBucket: 'internship-to-app.firebasestorage.app',
    iosBundleId: 'com.example.appBottomBar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_yaPdOtY2cCGf15Q-uzboIsY4sqR6OIE',
    appId: '1:1048561776711:web:a01d94b6f0dc827c39d962',
    messagingSenderId: '1048561776711',
    projectId: 'internship-to-app',
    authDomain: 'internship-to-app.firebaseapp.com',
    storageBucket: 'internship-to-app.firebasestorage.app',
    measurementId: 'G-D9EY2WN28K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2hAIPF2ycyV3DiUAhrlJJ-9DtVwUV6I',
    appId: '1:1048561776711:android:a16b262cd7d35a1c39d962',
    messagingSenderId: '1048561776711',
    projectId: 'internship-to-app',
    storageBucket: 'internship-to-app.firebasestorage.app',
  );

}